export const turnJsonSchema = {
  name: "advisor_turn",
  strict: false,
  schema: {
    type: "object",
    additionalProperties: false,
    required: [
      "candidate_message",
      "current_chapter",
      "extracted_candidate_data",
      "confidence_by_field",
      "contradictions_detected",
      "follow_up_reason",
      "next_question",
      "suggested_answers",
      "input_mode",
      "ready_for_thesis",
      "safety_flags",
      "asked_for_contact",
      "financial_disclaimer_needed",
    ],
    properties: {
      candidate_message: { type: "string" },
      current_chapter: {
        type: "string",
        enum: [
          "why_now",
          "ideal_life",
          "owner_role",
          "financial_reality",
          "strengths_preferences",
          "family_constraints",
          "risk_decision_style",
          "ownership_thesis",
        ],
      },
      extracted_candidate_data: {
        type: "object",
        additionalProperties: false,
        required: [
          "firstName",
          "lastName",
          "email",
          "phone",
          "city",
          "state",
          "whyOwnershipNow",
          "currentCareerOrBusiness",
          "desiredChange",
          "idealDay",
          "desiredWeeklyInvolvement",
          "preferredOwnerRole",
          "incomeGoal",
          "incomeReplacementTimeline",
          "liquidCapitalRange",
          "comfortableInvestmentAmount",
          "financingInterest",
          "minimumEmergencyReserve",
          "spouseOrPartnerAlignment",
          "geographicRequirements",
          "employeeTolerance",
          "salesComfort",
          "communityInvolvementPreference",
          "b2bVsConsumer",
          "recurringRevenuePreference",
          "brickAndMortarTolerance",
          "buildoutTolerance",
          "desiredNumberOfLocations",
          "riskTolerance",
          "decisionStyle",
          "timelineToAct",
          "mainConcerns",
          "statedNonNegotiables",
        ],
        properties: Object.fromEntries(
          [
            "firstName",
            "lastName",
            "email",
            "phone",
            "city",
            "state",
            "whyOwnershipNow",
            "currentCareerOrBusiness",
            "desiredChange",
            "idealDay",
            "desiredWeeklyInvolvement",
            "preferredOwnerRole",
            "incomeGoal",
            "incomeReplacementTimeline",
            "liquidCapitalRange",
            "comfortableInvestmentAmount",
            "financingInterest",
            "minimumEmergencyReserve",
            "spouseOrPartnerAlignment",
            "geographicRequirements",
            "employeeTolerance",
            "salesComfort",
            "communityInvolvementPreference",
            "b2bVsConsumer",
            "recurringRevenuePreference",
            "brickAndMortarTolerance",
            "buildoutTolerance",
            "desiredNumberOfLocations",
            "riskTolerance",
            "decisionStyle",
            "timelineToAct",
            "mainConcerns",
            "statedNonNegotiables",
          ].map((key) => [key, { type: ["string", "null"] }]),
        ),
      },
      confidence_by_field: {
        type: "object",
        additionalProperties: { type: "number" },
      },
      contradictions_detected: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          required: ["tension", "question"],
          properties: {
            tension: { type: "string" },
            question: { type: "string" },
          },
        },
      },
      follow_up_reason: { type: ["string", "null"] },
      next_question: { type: "string" },
      suggested_answers: { type: "array", items: { type: "string" } },
      input_mode: {
        type: "string",
        enum: ["written", "written_with_suggestions", "ranked", "range", "tradeoff", "scenario"],
      },
      ready_for_thesis: { type: "boolean" },
      safety_flags: { type: "array", items: { type: "string" } },
      asked_for_contact: { type: "boolean" },
      financial_disclaimer_needed: { type: "boolean" },
    },
  },
} as const;

const thesisSection = {
  type: "object",
  additionalProperties: false,
  required: ["title", "body", "indicator"],
  properties: {
    title: { type: "string" },
    body: { type: "string" },
    indicator: {
      type: ["string", "null"],
      enum: [
        "Strong alignment",
        "Worth exploring",
        "Requires clarification",
        "Potential conflict",
        "Higher-risk assumption",
        null,
      ],
    },
  },
};

export const thesisJsonSchema = {
  name: "ownership_thesis",
  strict: true,
  schema: {
    type: "object",
    additionalProperties: false,
    required: [
      "whyOwnershipIsBeingConsidered",
      "whatCandidateWantsOwnershipToCreate",
      "recommendedOwnerRole",
      "financialFramework",
      "businessCharacteristicsThatMayFit",
      "businessCharacteristicsToApproachCarefully",
      "strengthsTheCandidateBrings",
      "potentialConflictsOrBlindSpots",
      "questionsStillRequiringHumanJudgment",
      "recommendedNextStep",
      "namedBrands",
      "conclusion",
    ],
    properties: {
      whyOwnershipIsBeingConsidered: thesisSection,
      whatCandidateWantsOwnershipToCreate: thesisSection,
      recommendedOwnerRole: thesisSection,
      financialFramework: thesisSection,
      businessCharacteristicsThatMayFit: thesisSection,
      businessCharacteristicsToApproachCarefully: thesisSection,
      strengthsTheCandidateBrings: thesisSection,
      potentialConflictsOrBlindSpots: thesisSection,
      questionsStillRequiringHumanJudgment: thesisSection,
      recommendedNextStep: thesisSection,
      namedBrands: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          required: ["name", "reason", "disclaimer"],
          properties: {
            name: { type: "string" },
            reason: { type: "string" },
            disclaimer: { type: "string" },
          },
        },
      },
      conclusion: { type: "string" },
    },
  },
} as const;

export const briefJsonSchema = {
  name: "meeting_brief",
  strict: true,
  schema: {
    type: "object",
    additionalProperties: false,
    required: [
      "candidateInOneParagraph",
      "whatTheySayTheyWant",
      "whatTheyMayActuallyBeSolvingFor",
      "financialReality",
      "familyOrLifestyleConstraints",
      "contradictionsToExplore",
      "likelyDecisionStyle",
      "suitableBusinessModelCharacteristics",
      "modelsToApproachCarefully",
      "threeQuestionsChuckShouldAskNext",
      "suggestedOpeningForTheStrategyCall",
      "suggestedFollowUpEmail",
    ],
    properties: {
      candidateInOneParagraph: { type: "string" },
      whatTheySayTheyWant: { type: "string" },
      whatTheyMayActuallyBeSolvingFor: { type: "string" },
      financialReality: { type: "string" },
      familyOrLifestyleConstraints: { type: "string" },
      contradictionsToExplore: { type: "string" },
      likelyDecisionStyle: { type: "string" },
      suitableBusinessModelCharacteristics: { type: "string" },
      modelsToApproachCarefully: { type: "string" },
      threeQuestionsChuckShouldAskNext: { type: "array", items: { type: "string" } },
      suggestedOpeningForTheStrategyCall: { type: "string" },
      suggestedFollowUpEmail: { type: "string" },
    },
  },
} as const;
